version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: echo
          command: echo "Hello word2" 

workflows:
    test_workflows:
      jobs:
        - test